### PR TITLE
Create strandSort.cpp

### PR DESCRIPTION
**Pull request by brat00**
This file containing strand sort algorithm in c++ language

### CODE REVIEW

**Comment by AnanyaDas162** [comment]
Hello @brat00 , here in this PR, I can see that 26 files have been changed. So, you please pull the origin of this repository and then create PR with your strandSort.cpp file.

**Comment by brat00** [comment]
@AnanyaDas162 actually i try to solve the issue #68 that's why i also rearrange the file as when finally i update it it goes with my last pr i think  please review changes you can merge this will not cause any harm to your current repo

**Comment by brat00** [comment]
also i want a help how can i show my repository which i forked from your one so that i can show the folder to rearrange file

**Comment by brat00** [comment]
you can see i moved the files  to a folder name "important problems in cp"

**Comment by AnanyaDas162** [comment]
@brat00 , yeah, but now you can see there are separate folders and inside them the corresponding files are located. So by merging this, the total folder division will be changed. So I am closing this PR and you please send a different PR for this sorting algorithm. And also thanks to you for collaborating in this repo. Meet you again!

**Comment by brat00** [comment]
@AnanyaDas162  thanks to you surely i will do that

**Pull request closed without merging**
